### PR TITLE
added Teck Stack 

### PR DESCRIPTION
**Pull request by shravya312**

### CODE REVIEW

**Comment by shravya312** [comment]
Can u review the changes made and add labels to pr too, Thank you @Devanik21

**Comment by Devanik21** [comment]
> @Devanik21 can u review the changes

Yes, its cool, Thanks
I added - **App Framework:** Streamlit for rapid web app development.

**Comment by shravya312** [comment]
Can u please add gssoc extended, hactoberfest accepted, and level label to pr else it wont be considered as contributed itseems
@Devanik21

**Comment by shravya312** [comment]
Can u please add the labels leader board is live this pr is not counted @Devanik21

**Comment by shravya312** [comment]
Can u add the labels to the pr. the leader board is live this pr is not considered

**Comment by shravya312** [comment]
Thanks a lot for adding the labels Can u also add hactoberfest-accepted 
I am working on the other issue I will pr as soon as it is done 😇

**Pull request merged**
