### PR TITLE
Water Potablity Project 

### PR DESCRIPTION
**Pull request by SimranShaikh20**
Issue no - #78 
Added one entire projects with all mandatory file.
@Devanik21  is there any conflicts then let me know .

### CODE REVIEW

**Comment by Devanik21** [comment]
@SimranShaikh20 ,yes auto label.yml conflicting all pr

**Comment by SimranShaikh20** [comment]
> @SimranShaikh20 ,yes auto label.yml conflicting all pr

So i have time make new pr for that? 
@Devanik21

**Comment by SimranShaikh20** [comment]
@Devanik21 i think label issue is from your side !
can you pls check it becoz i had check my branch and entire folder but there not issue in it !

**Comment by Devanik21** [comment]
@SimranShaikh20 

@github-actions
Auto Label Issue and PR / label_issue_or_pr (pull_request) Failing after 2s

**Comment by SimranShaikh20** [comment]
@Devanik21  i will make new pr

**Pull request closed without merging**
