### PR TITLE
Changed the deep learning framework from tensorflow to pytorch

### PR DESCRIPTION
**Pull request by shravya312**
#18 
image
image

### CODE REVIEW

**Comment by Devanik21** [comment]
@shravya312 , interesting, but can we be benefited from it ?

**Comment by Devanik21** [comment]
can we add more features to our model ?

**Comment by shravya312** [comment]
A dynamic computation graph is a key feature of PyTorch that allows the framework to create a map of calculations while the program is running.

Key Points:
Built While Running: The graph is formed as you run your code, not before. This means it can change every time you execute it.

Flexible and Adaptive: You can easily change how your model behaves based on the data you provide. For example, if the input data is different, the graph adjusts accordingly.

Easy to Debug: Since the graph is created as the code runs, you can use regular Python tools to check for errors right where they happen, making it easier to fix problems. these are the features of pytorch which is beneficial

**Comment by shravya312** [comment]
> can we add more features to our model ?

Educational Resources
Learning Modules: Offer tutorials or modules that educate users on space mining, including best practices and case studies.
Resource Library: Create a library of articles, research papers, and case studies related to space mining and exploration.

**Comment by shravya312** [comment]
> > can we add more features to our model ?
> 
> Educational Resources Learning Modules: Offer tutorials or modules that educate users on space mining, including best practices and case studies. Resource Library: Create a library of articles, research papers, and case studies related to space mining and exploration.

this can be done using deep-learning which can use the mining data and results from this model to educate people

**Comment by shravya312** [comment]
I have done this in different file @Devanik21

**Comment by shravya312** [comment]
Can u review @Devanik21 if any changes needed I will do

**Pull request merged**
