### PR TITLE
Added weights Adjustment Functionality, reset functionality, error handling for model loading

### PR DESCRIPTION
**Pull request by Kritika75**
1. Error Handling: Added error handling when loading the model with joblib.load(), providing user feedback for missing model files or other loading errors.

2. Feature Adjustment: Introduced a new function, adjust_weights(), which modifies feature weights based on iron content and other parameters, including logic for winsorizing iron values and adjusting weights according to defined thresholds.

3. Input Reset Functionality: Implemented a reset_inputs() function that allows users to reset all input values to their defaults, accessible through the sidebar.

hey @Devanik21 please check the code and let me know also please provide me the level tags on my issue (#27 )and om my pull request also please
Thank you!

### CODE REVIEW

**Comment by Devanik21** [comment]
> 1. Error Handling: Added error handling when loading the model with joblib.load(), providing user feedback for missing model files or other loading errors.
> 2. Feature Adjustment: Introduced a new function, adjust_weights(), which modifies feature weights based on iron content and other parameters, including logic for winsorizing iron values and adjusting weights according to defined thresholds.
> 3. Input Reset Functionality: Implemented a reset_inputs() function that allows users to reset all input values to their defaults, accessible through the sidebar.
> 
> hey @Devanik21 please check the code and let me know also please provide me the level tags on my issue (#27 )and om my pull request also please Thank you!

plz can u actually discuss what has changed, I couldn't get it.
plz attach screenshots

**Comment by Devanik21** [comment]
I've predicted, but its same only, no adjustment of weights.

**Comment by Kritika75** [comment]
@Devanik21 can you check now Adjust Weights: modify the weights based on certain thresholds (Iron, Nickel, Water Ice) using the adjust_weights() function.
Apply Weights, before making predictions, apply these adjusted weights to the feature values with the apply_weights() function.
Prediction, we pass the weighted feature values to the model for prediction instead of the raw features.

**Comment by Devanik21** [comment]
> actually in the previous code the logic isn’t integrated into the model prediction. The adjusted weights are not being used by the model when making a prediction, which is why the prediction remains unchanged.I've incorporated the adjusted weights into the feature data before making the prediction, possibly modify the model to take these adjusted weights into account. mining this the change i made in 3rd commit

Keep it up, but @Kritika75 , can u share screenshots of the updated functionality during prediction?

**Comment by Kritika75** [comment]
Sure, I'll share it by tomorrow

**Comment by Devanik21** [comment]
> Sure, I'll share it by tomorrow

yes plz

**Comment by Kritika75** [comment]
Hey, I'm trying to add the ss but is showing the error it happened with me before also, I'll try later to add it but can you tell what you can't get like i can tell you whole breakdown of the code and how's different from previous one and what you can expect from it @Devanik21

**Comment by Devanik21** [comment]
@Kritika75 , i reviewed the code, its alright. But no change seen.

**Comment by Devanik21** [comment]
@Kritika75 , help , its showing error
image

**Pull request merged**
